"""tags and base with unique

Revision ID: 51507ba80c1f
Revises: 
Create Date: 2022-04-11 21:29:35.777232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51507ba80c1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_rel', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_rel', name='uniq_tags_id_user_rel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
